const fs = require("fs")
const path = require("path")
const { normalizeAptechTarget } = require("../pages/aptech/utils/aptechTargetCorrections")

const inputPath = path.join(
  __dirname,
  "../outputs/aptech_model_compare/test_runs/20260630_aptech_price_list/aptech_price_model_test_vigour_display.csv"
)
const outputPath = path.join(
  __dirname,
  "../pages/aptech/utils/aptechSearchDatabase.js"
)

function parseCsv(text) {
  const rows = []
  let row = []
  let field = ""
  let quoted = false

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index]
    const next = text[index + 1]

    if (quoted) {
      if (char === "\"" && next === "\"") {
        field += "\""
        index += 1
      } else if (char === "\"") {
        quoted = false
      } else {
        field += char
      }
      continue
    }

    if (char === "\"") {
      quoted = true
    } else if (char === ",") {
      row.push(field)
      field = ""
    } else if (char === "\n") {
      row.push(field.replace(/\r$/, ""))
      rows.push(row)
      row = []
      field = ""
    } else {
      field += char
    }
  }

  if (field || row.length) {
    row.push(field.replace(/\r$/, ""))
    rows.push(row)
  }

  return rows
}

function buildRows(csvRows) {
  const [headerRow, ...bodyRows] = csvRows
  const headers = headerRow.map((header) => header.replace(/^\uFEFF/, ""))
  const cleanIndex = headers.indexOf("clean_model_for_test")
  const vigourIndex = headers.indexOf("vigour_model_display")

  if (cleanIndex < 0 || vigourIndex < 0) {
    throw new Error("APTech display CSV is missing required columns")
  }

  const seen = new Set()
  const rows = []

  bodyRows.forEach((row) => {
    const sourceModel = (row[cleanIndex] || "").trim()
    const vigourModel = normalizeAptechTarget((row[vigourIndex] || "").trim(), sourceModel)
    if (!sourceModel) return

    const key = `${sourceModel}\u0000${vigourModel}`
    if (seen.has(key)) return
    seen.add(key)
    rows.push(["APTech", sourceModel, vigourModel, vigourModel ? 0 : 1])
  })

  return rows
}

const csv = fs.readFileSync(inputPath, "utf8")
const rows = buildRows(parseCsv(csv))
const body = `// Generated by tools/build_aptech_search_database.js from APTech price-list test output.\nmodule.exports=${JSON.stringify(rows)}\n`

fs.writeFileSync(outputPath, body)
console.log(`Wrote ${rows.length} APTech search rows to ${outputPath}`)
